name: Your New Jekyll Site
markdown: redcarpet
highlighter: rouge # or rouge or null
exclude: [
  # Project files
  "gulpfile.babel.js",
  "package.json",
  "tsconfig.json",
  "Gemfile",

  # Source files
  "_pug",
  "_scss",
  "_ts",

  # Generated
  "node_modules",
  "params.json",
  "yarn.lock",
  "Gemfile.lock",

  # Project information
  "CODEOWNERS",
  "README.md",
  "LICENSE"
]
